### ISSUE TITLE
Puppet server can't connect to puppet db

### ISSUE THREAD

**Issue by markhowells** [puppetlabs/puppet-in-docker-examples#12]
I'm using a compose file to launch a puppet stack as follows
```
version: '2'
services:
  puppet:
    container_name: puppet
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - 8140:8140
    volumes:
      - ./code:/etc/puppetlabs/code/
      - ./puppet/ssl:/etc/puppetlabs/puppet/ssl/
      - ./puppet/serverdata:/opt/puppetlabs/server/data/puppetserver/
    # In some cases unqualified hostnames can have the .local suffix
    # added, I've seen this under Docker of Mac Beta for instance.
    # Due to needing to access PuppetDB on same hostame as signed in the
    # certificate you may need to uncommant the following lines
    # environment:
      # - PUPPETDB_SERVER_URLS=https://puppetdb.mydomain.net:8081
    #links:
    #  - puppetdb:puppetdb.local
  puppetdbpostgres:
    container_name: postgres
    image: puppet/puppetdb-postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    expose:
      - 5432
    volumes:
      - ./puppetdb-postgres/data:/var/lib/postgresql/data/
  puppetdb:
    container_name: puppetdb
    hostname: puppetdb
    image: puppet/puppetdb
    ports:
      - 7080:8080
      - 7081:8081
    volumes:
      - ./puppetdb/ssl:/etc/puppetlabs/puppet/ssl/
  puppetboard:
    container_name: puppetboard
    image: puppet/puppetboard
    ports:
      - 6080:8000
  puppetexplorer:
    container_name: puppetexplorer
    image: puppet/puppetexplorer
    ports:
      - 5080:80
    read_only: true
```

Essentially it's the same as your example, but with some ports exposed/mapped. Each container is able to reference the others by container name (via ping and/or telnetting to an appropriate service port)

However, the puppetserver is unable to call puppetdb - here's a snippet from the puppetserver log
```
2017-01-23 09:39:19,180 INFO  [puppetserver] Puppet Caching facts for puppetdb
2017-01-23 09:39:19,202 ERROR [c.p.h.c.i.PersistentSyncHttpClient] Error executing http request
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:173)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:147)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:350)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:191)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
        at java.lang.Thread.run(Thread.java:745)
2017-01-23 09:39:19,208 WARN  [puppetserver] Puppet Error connecting to puppetdb on 8081 at route /pdb/cmd/v1?checksum=89d651b5803f5911f312d2050dabdeb7afa5cf43&version=5&certname=puppetdb&command=replace_facts, error message received was 'Error executing http request'. Failing over to the next PuppetDB server_url in the 'server_urls' list
2017-01-23 09:39:19,210 ERROR [puppetserver] Puppet Failed to execute '/pdb/cmd/v1?checksum=89d651b5803f5911f312d2050dabdeb7afa5cf43&version=5&certname=puppetdb&command=replace_facts' on at least 1 of the following 'server_urls': https://puppetdb:8081
```

If I exec into the puppet server and attempt a to use wget to connect I see
```
root@puppet:/# wget https://puppetdb:8081
--2017-01-23 09:12:03--  https://puppetdb:8081/
Resolving puppetdb (puppetdb)... 172.21.0.5
Connecting to puppetdb (puppetdb)|172.21.0.5|:8081... connected.
Unable to establish SSL connection.
root@puppet:/#
```

and using openssl to debug the connection from withing the server container

    openssl s_client -connect puppetdb:8081 -prexit

I can see that it's a cert verification error ( [full output](http://pastebin.com/Xsc2dapD) )
```
CONNECTED(00000003)
depth=0 CN = puppetdb
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = puppetdb
verify error:num=21:unable to verify the first certificate
verify return:1
139925684668056:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
Certificate chain
 0 s:/CN=puppetdb
   i:/CN=Puppet CA: puppet
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFYTCCA0mgAwIBAgIBAzANBgkqhk
...
```

As far as I can see ( I'm not very familiar with administering puppetdb ) puppetDB looks ok ( [log ](http://pastebin.com/hdeDbcxb))

So, I'm stumped.

Any help would be appreciated.

**Comment by markhowells** [comment]
Showing my ignorance a little, I now realise that I needed to supply the certs/ca info to openssl

    openssl s_client -debug -connect puppetdb:8081 -prexit -CApath /etc/puppetlabs/puppet/ssl/certs -CAfile /etc/puppetlabs/puppet/ssl/certs/ca.pem

This now works as expected (i.e. it connects just fine).  So I'm even more puzzled about why I am seeing the errors in the puppet logs.  I've mounted the volume into the right place ?  Is puppet server looking elsewhere by default?

**Comment by markhowells** [comment]
And using wget with cert checking disabled also fails (probably what I expected).
```
root@puppet:/etc/puppetlabs/puppet/ssl/certs# wget -d -v --no-check-certificate https://puppetdb:8081
Setting --verbose (verbose) to 1
Setting --check-certificate (checkcertificate) to 0
DEBUG output created by Wget 1.17.1 on linux-gnu.
Reading HSTS entries from /root/.wget-hsts
URI encoding = 'ANSI_X3.4-1968'
converted 'https://puppetdb:8081' (ANSI_X3.4-1968) -> 'https://puppetdb:8081' (UTF-8)
--2017-01-23 15:36:59--  https://puppetdb:8081/
Resolving puppetdb (puppetdb)... 172.18.0.6
Caching puppetdb => 172.18.0.6
Connecting to puppetdb (puppetdb)|172.18.0.6|:8081... connected.
Created socket 3.
Releasing 0x000055f4213f0600 (new refcount 1).
Initiating SSL handshake.
SSL handshake failed.
Closed fd 3
Unable to establish SSL connection.
Saving HSTS entries to /root/.wget-hsts
```
So that would point to a broken protocol request wouldn't it?  I've also tried forcing wget to use TLSv1 but it still doesn't work.

**Comment by markhowells** [comment]
For reference, I finally solved this issue myself. I had to exec'd into the puppetdb container and ran
```
puppet agent --test --noop --certname puppetdb
```
From this point onward everything works as expected...

Is this a bug or just something I have to arrange myself?

**Comment by kirkins** [comment]
I opened a new issue but realizing it is actually the same as this one:

https://github.com/puppetlabs/puppet-in-docker-examples/issues/13

Tried the last command you mentioned, which works successfully but didn't seem to fix the issue on my setup.

**Comment by kirkins** [comment]
I ended up fixing my issue by combining the two commands posted here and changing the name `puppetdb` to `puppetdb.myOrganization`.

https://github.com/puppetlabs/puppet-in-docker-examples/issues/13

**Comment by cmachler** [comment]
I fixed my issue because it was adding by adding `dns_search: .` to the puppetdb service because it was adding the dns suffix from my host machine to the puppetdb certificate.

**Comment by checksrc** [comment]
@garethr Any thoughts? 

Puppet-DB Log
```
2017-6-7 18:48:172017-06-07 17:48:17,715 INFO  [c.z.h.HikariDataSource] PDBMigrationsPool - is starting.
2017-6-7 18:48:2010.42.218.130 - - [07/Jun/2017:17:48:20 +0000] "GET / HTTP/1.1" 200 0 "-" "-"
2017-6-7 18:48:2010.42.218.130 - - [07/Jun/2017:17:48:20 +0000] "GET / HTTP/1.1" 200 0 "-" "-"
2017-6-7 18:48:322017-06-07 17:48:32,716 INFO  [c.z.h.p.HikariPool] PDBMigrationsPool - is closing down.
2017-6-7 18:48:372017-06-07 17:48:37,189 ERROR [p.p.c.services] Error while attempting to create connection pool
2017-6-7 18:48:37java.sql.SQLTransientConnectionException: PDBMigrationsPool - Connection is not available, request timed out after 15000ms.
2017-6-7 18:48:37	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:195) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:281) ~[na:na]
2017-6-7 18:48:37	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:176) ~[na:na]
2017-6-7 18:48:37	at puppetlabs.puppetdb.cli.services$initialize_schema.invokeStatic(services.clj:303) ~[na:na]
2017-6-7 18:48:37	at puppetlabs.puppetdb.cli.services$initialize_schema.invoke(services.clj:297) ~[na:na]
2017-6-7 18:48:37	at puppetlabs.puppetdb.cli.services$init_with_db$fn__36693.invoke(services.clj:329) ~[na:na]
2017-6-7 18:48:37	at puppetlabs.puppetdb.cli.services$init_with_db.invokeStatic(services.clj:325) [na:na]
2017-6-7 18:48:37	at puppetlabs.puppetdb.cli.services$init_with_db.invoke(services.clj:310) [na:na]
2017-6-7 18:48:37	at puppetlabs.puppetdb.cli.services$start_puppetdb.invokeStatic(services.clj:359) [na:na]
2017-6-7 18:48:37	at puppetlabs.puppetdb.cli.services$start_puppetdb.invoke(services.clj:336) [na:na]
2017-6-7 18:48:37	at puppetlabs.puppetdb.cli.services$reify__36800$service_fnk__11406__auto___positional$reify__36809.start(services.clj:452) [na:na]
2017-6-7 18:48:37	at puppetlabs.trapperkeeper.services$eval11212$fn__11226$G__11202__11229.invoke(services.clj:8) [na:na]
2017-6-7 18:48:37	at puppetlabs.trapperkeeper.services$eval11212$fn__11226$G__11201__11233.invoke(services.clj:8) [na:na]
2017-6-7 18:48:37	at puppetlabs.trapperkeeper.internal$eval19156$run_lifecycle_fn_BANG___19163$fn__19164.invoke(internal.clj:177) [na:na]
2017-6-7 18:48:37	at puppetlabs.trapperkeeper.internal$eval19156$run_lifecycle_fn_BANG___19163.invoke(internal.clj:160) [na:na]
2017-6-7 18:48:37	at puppetlabs.trapperkeeper.internal$eval19185$run_lifecycle_fns__19190$fn__19191.invoke(internal.clj:211) [na:na]
2017-6-7 18:48:37	at puppetlabs.trapperkeeper.internal$eval19185$run_lifecycle_fns__19190.invoke(internal.clj:188) [na:na]
2017-6-7 18:48:37	at puppetlabs.trapperkeeper.internal$eval19655$build_app_STAR___19664$fn$reify__19674.start(internal.clj:564) [na:na]
2017-6-7 18:48:37	at puppetlabs.trapperkeeper.internal$eval19701$boot_services_for_app_STAR__STAR___19708$fn__19709$fn__19711.invoke(internal.clj:588) [na:na]
2017-6-7 18:48:37	at puppetlabs.trapperkeeper.internal$eval19701$boot_services_for_app_STAR__STAR___19708$fn__19709.invoke(internal.clj:586) [na:na]
2017-6-7 18:48:37	at puppetlabs.trapperkeeper.internal$eval19701$boot_services_for_app_STAR__STAR___19708.invoke(internal.clj:580) [na:na]
2017-6-7 18:48:37	at clojure.core$partial$fn__4761.invoke(core.clj:2521) [puppetdb.jar:na]
2017-6-7 18:48:37	at puppetlabs.trapperkeeper.internal$eval19224$initialize_lifecycle_worker__19235$fn__19236$fn__19322$state_machine__17201__auto____19323$fn__19325.invoke(internal.clj:228) [na:na]
2017-6-7 18:48:37	at puppetlabs.trapperkeeper.internal$eval19224$initialize_lifecycle_worker__19235$fn__19236$fn__19322$state_machine__17201__auto____19323.invoke(internal.clj:228) [na:na]
2017-6-7 18:48:37	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:1011) [na:na]
2017-6-7 18:48:37	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:1010) [na:na]
2017-6-7 18:48:37	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:1015) [na:na]
2017-6-7 18:48:37	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:1013) [na:na]
2017-6-7 18:48:37	at clojure.core.async$ioc_alts_BANG_$fn__17369.invoke(async.clj:378) [na:na]
2017-6-7 18:48:37	at clojure.core.async$do_alts$fn__17315$fn__17318.invoke(async.clj:247) [na:na]
2017-6-7 18:48:37	at clojure.core.async.impl.channels.ManyToManyChannel$fn__12125$fn__12126.invoke(channels.clj:95) [na:na]
2017-6-7 18:48:37	at clojure.lang.AFn.run(AFn.java:22) [puppetdb.jar:na]
2017-6-7 18:48:37	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
2017-6-7 18:48:37	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
2017-6-7 18:48:37	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
2017-6-7 18:48:37Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
2017-6-7 18:48:37	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:215) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at org.postgresql.Driver.makeConnection(Driver.java:406) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at org.postgresql.Driver.connect(Driver.java:274) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:314) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:171) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:436) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at com.zaxxer.hikari.pool.HikariPool.access$500(HikariPool.java:65) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:567) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:560) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_91]
2017-6-7 18:48:37	... 3 common frames omitted
2017-6-7 18:48:37Caused by: java.net.UnknownHostException: postgres
2017-6-7 18:48:37	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_91]
2017-6-7 18:48:37	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_91]
2017-6-7 18:48:37	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_91]
2017-6-7 18:48:37	at org.postgresql.core.PGStream.<init>(PGStream.java:64) ~[puppetdb.jar:na]
2017-6-7 18:48:37	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:133) ~[puppetdb.jar:na]
2017-6-7 18:48:37	... 16 common frames omitted
2017-6-7 18:48:372017-06-07 17:48:37,190 INFO  [c.z.h.HikariDataSource] PDBMigrationsPool - is starting.
2017-6-7 18:48:5010.42.218.130 - - [07/Jun/2017:17:48:50 +0000] "GET / HTTP/1.1" 200 0 "-" "-"
2017-6-7 18:48:5010.42.218.130 - - [07/Jun/2017:17:48:50 +0000] "GET / HTTP/1.1" 200 0 "-" "-"
2017-6-7 18:48:522017-06-07 17:48:52,192 INFO  [c.z.h.p.HikariPool] PDBMigrationsPool - is closing down. 
```
Puppet-Server Log
```
2017-6-7 18:43:562017-06-07 17:43:56,086 WARN  [puppetserver] Puppet Error connecting to puppetdb.local on 8081 at route /pdb/cmd/v1?checksum=fce0a354c52e207ec971e858e5c2791f4ab668f6&version=5&certname=puppetdb&command=replace_facts, error message received was 'Error executing http request'. Failing over to the next PuppetDB server_url in the 'server_urls' list
2017-6-7 18:43:562017-06-07 17:43:56,087 ERROR [puppetserver] Puppet Failed to execute '/pdb/cmd/v1?checksum=fce0a354c52e207ec971e858e5c2791f4ab668f6&version=5&certname=puppetdb&command=replace_facts' on at least 1 of the following 'server_urls': https://puppetdb.local:8081
2017-6-7 18:43:562017-06-07 17:43:56,088 INFO  [puppetserver] Puppet Caching node for puppetdb
2017-6-7 18:43:562017-06-07 17:43:56,794 WARN  [puppetserver] Puppet Class 'settings' is already defined; cannot redefine at :
2017-6-7 18:43:562017-06-07 17:43:56,817 INFO  [puppetserver] Puppet Compiled catalog for puppetdb in environment production in 0.03 seconds
2017-6-7 18:43:562017-06-07 17:43:56,818 INFO  [puppetserver] Puppet Caching catalog for puppetdb
2017-6-7 18:43:562017-06-07 17:43:56,999 ERROR [c.p.h.c.i.PersistentSyncHttpClient] Error executing http request
2017-6-7 18:43:56javax.net.ssl.SSLPeerUnverifiedException: Host name 'puppetdb.local' does not match the certificate subject provided by the peer (CN=puppetdb.puppet-server.rancher.internal)
2017-6-7 18:43:56	at org.apache.http.nio.conn.ssl.SSLIOSessionStrategy.verifySession(SSLIOSessionStrategy.java:208)
2017-6-7 18:43:56	at org.apache.http.nio.conn.ssl.SSLIOSessionStrategy$1.verify(SSLIOSessionStrategy.java:188)
2017-6-7 18:43:56	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:366)
2017-6-7 18:43:56	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:507)
2017-6-7 18:43:56	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:122)
2017-6-7 18:43:56	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:164)
2017-6-7 18:43:56	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:339)
2017-6-7 18:43:56	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:317)
2017-6-7 18:43:56	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:278)
2017-6-7 18:43:56	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
2017-6-7 18:43:56	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
2017-6-7 18:43:56	at java.lang.Thread.run(Thread.java:745)
```

This happens both at initial startup and using both of @markhowells commands that are listed above. 

My docker-compose  - the only things I'm changing are the puppet server SSH port.
Apart from that, other variables have their default entries (in a rancher-compose.yml - because I use rancher-server.)

```
version: '2'

services:
  puppet:
    container_name: puppet
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - 8140:8140
      - ${SERVER_SSH}:22
    volumes:
      - /srv/code:/etc/puppetlabs/code/
      - /srv/puppet/ssl:/etc/puppetlabs/puppet/ssl/
      - /srv/puppet/serverdata:/opt/puppetlabs/server/data/puppetserver/
    # In some cases unqualified hostnames can have the .local suffix
    # added, I've seen this under Docker of Mac Beta for instance.
    # Due to needing to access PuppetDB on same hostame as signed in the
    # certificate you may need to uncommant the following lines
    environment:
      - PUPPETDB_SERVER_URLS=https://${PUPPET_DB_URL}:${PUPPET_DB_PORT}
    links:
      - puppetdb:puppetdb.local
    
  puppetdbpostgres:
    container_name: postgres
    image: puppet/puppetdb-postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    expose:
      - 5432
    volumes:
      - /srv/puppet/puppetdb-postgres/data:/var/lib/postgresql/data/

  puppetdb:
    hostname: puppetdb
    image: puppet/puppetdb
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - /srv/puppet/puppetdb/ssl:/etc/puppetlabs/puppet/ssl/

  puppetboard:
    image: puppet/puppetboard
    ports:
      - 8000:8000

  puppetexplorer:
    image: puppet/puppetexplorer
    ports:
      - 80
    read_only: true
```
My server is
```
Docker-  17.03.1-ce
 Ubuntu 16.04.2 LTS (with KVM) (4.8.0)
 8x3.07 GHz
 47.2 GiB
 1.77 TiB
```
